name: Deploy app

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
    run-deploy-app:
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2

        # Setup nodejs
        - name: Setup Node.js 18v
          uses: actions/setup-node@v1
          with:
            node-version: "18.x"
      
        # Install all packages
        - name: Setup dependencies
          run: npm install --frozen-lockfile
        
        # Building the project
        - name: Building the project
          run: npm run build

        # Testing
        - name: Check files
          run: ls

        # Deploy to github pages
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./dist

